AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating infrastructure including Secrets Manager'

Parameters:
  DBUsername:
    Type: String
    Description: Database username
  DBPassword:
    Type: String
    Description: Database password
    NoEcho: true

Resources:
  # Existing resources...

  # New ECR Repository
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AWS::StackName}-repo
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true

  # Secrets Manager Secret
  DatabaseSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: 'your-app-db-secret'
      Description: 'Database credentials for your-app'
      SecretString: 
        !Join 
          - ''
          - - '{"username":"'
            - !Ref DBUsername
            - '","password":"'
            - !Ref DBPassword
            - '"}'

  # IAM Role for EKS nodes to access Secrets Manager
  EKSNodeRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy'
        - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'secretsmanager:GetSecretValue'
                Resource: !Ref DatabaseSecret

Outputs:
  # Existing outputs...

  ECRRepositoryUri:
    Description: The URI of the ECR repository
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}
    Export:
      Name: !Sub ${AWS::StackName}-ECRRepositoryUri

  SecretARN:
    Description: 'ARN of the created secret'
    Value: !Ref DatabaseSecret
  EKSNodeRoleARN:
    Description: 'ARN of the EKS Node Role'
    Value: !GetAtt EKSNodeRole.Arn
