apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  username: your_aws_db_username
  secret-arn: arn:aws:secretsmanager:${aws-region}:${account-id}:secret:your-secret-name
